# Site settings
title: Moody Sprout
email: info@moodysprout.com
description: > 
  A personal blog about diy projects, papercraft, handmade goodies, and much more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://moodysprout.com" # the base hostname & protocol for your site
instagram_username: moodycrafts
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
